### ISSUE TITLE
fatal error: libaio.h: No such file or directory

### ISSUE THREAD

**Issue by jinz2014** [VIDILabs/instantvnr#2]
cmake --build . --config Release --parallel

/path/to/open-volume-renderer/projects/instantvnr/core/samplers/neural_sampler.cpp:24:10: fatal error: libaio.h: No such file or directory
   24 | #include <libaio.h>

Thanks

**Comment by wilsonCernWq** [comment]
To build the out-of-core streaming backend, `libaio-dev` is needed. You should be able to install it via your OS package manager.

Alternatively, you can disable this feature by setting this flag to `OFF`
https://github.com/VIDILabs/instantvnr/blob/public/CMakeLists.txt#L62

We are currently working on an more optimized implementation of this out-of-core streaming backend.
